# Generated by Django 4.1.1 on 2022-09-20 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=50, verbose_name='Category name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price for a piece')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product name')),
                ('product_description', models.TextField(verbose_name='Description')),
                ('composition', models.TextField(verbose_name='Composition')),
                ('is_new', models.BooleanField(default=True, verbose_name='Is this product new')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is this product currently active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='A creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.category', verbose_name='Product category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
            },
        ),
    ]
