# Generated by Django 4.1.1 on 2022-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ManyToManyField(to='products.images', verbose_name='Image'),
        ),
    ]
