# Generated by Django 4.1.1 on 2022-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mass',
            field=models.PositiveIntegerField(default=100, verbose_name='Product mass in g'),
            preserve_default=False,
        ),
    ]
